import Head from "next/head";
import Header from "@/components/header";
import Footer from "@/components/footer";

export default function Layout({ children, metaDescription, metaTitle }) {
	return (
		<div>
			<Head>
				<title>{`Belajar Next - ${metaTitle}`}</title>
				<meta
					name="description"
					content={metaDescription || "Generated by Belajar Next"}
				/>
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<Header />
			<div>{children}</div>
			<Footer />
		</div>
	);
}
